# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Robot Framework Libdoc Generation

on:
  push:
    branches: [ "main" ]
  pull_request:
    types: [opened, reopened, synchronize]

permissions:
  contents: read
  checks: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Set up Python 3.12
      uses: actions/setup-python@v3
      with:
        python-version: "3.12"
    - name: Install dependencies
      run: |
        curl -sSL https://install.python-poetry.org | python3 -
        poetry install
    - name: Lint with ruff
      run: poetry run ruff check
    - name: Format with ruff
      run: poetry run ruff format --check
    - name: Generate Libdoc
      run: |
        mkdir -p docs
        find . -name '*.robot' -exec poetry run python -m robot.libdoc {} docs/{}.html \;
        find . -name '*.resource' -exec poetry run python -m robot.libdoc {} docs/{}.html \;
        find . -name '*.py' -exec poetry run python -m robot.libdoc {} docs/{}.html \;
    - name: Upload Libdoc
      uses: actions/upload-artifact@v4
      with:
        name: libdoc
        path: docs
